name: Tests, Code Quality, Build

on: [push, pull_request]

jobs:

  test:
    name: Run unit tests
    runs-on: [self-hosted,nodejs]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -e .[test]
      - name: Run test suite
        run: pytest --cov=order_matching

  code-quality:
    name: Code quality checks
    runs-on: [self-hosted,nodejs]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install dependencies
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run -v --show-diff-on-failure

  build-wheels:
    name: Build wheels
    runs-on: [self-hosted,nodejs]
    steps:
      - uses: actions/checkout@v3
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build-sdist:
    name: Build source distribution
    runs-on: [self-hosted,nodejs]
    steps:
      - uses: actions/checkout@v3
      - name: Build sdist
        run: |
          python -m pip install build
          python -m build --sdist
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.tar.gz

  upload-pypi:
    name: Upload to PyPi
    needs: [build-wheels, build-sdist]
    runs-on: [self-hosted,nodejs]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          # to test:
          repository_url: https://test.pypi.org/legacy/

  release:
    name: Release on GitHub
    needs: [build-wheels, build-sdist]
    runs-on: [self-hosted,nodejs]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
